const Main = DOMHandler('.inputContainer')
const inputWhite = CreateInput()
const text = CreateTitle('hola')
const titulito = DOMHandler('.notesContainer')
Main.load(inputWhite.render())
titulito.load(text.render())